# handlers file for percona-server
---
- name: restart percona-server
  service:
    name: mysql
    state: "{{ percona_restart_handler_state }}"
  when: percona_server_enable_handler_restart and service_default_state | default('started' == 'started')
